/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'job_refs.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'job_refs.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./job_refs.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("job").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.jobRefs",
    options: {
        tableName: "job_refs",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "job_refs_pkey"
        },
        "jobId": {
            type: Seq.BIGINT,
            field: "job_id",
            allowNull: false,
            references: "public.jobs",
            referencesKey: "job_id"
        },
        "type": {
            type: Seq.TEXT,
            field: "type"
        },
        "value": {
            type: Seq.TEXT,
            field: "value"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.jobs",
        schema: "public",
        table: "jobs",
        source: "generator",
        details: {
            as: "job",
            foreignKey: "job_id",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }]
};