/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'job_locations.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'job_locations.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./job_locations.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkJobXLocation1s").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.jobLocations",
    options: {
        tableName: "job_locations",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "job_locations_pkey"
        },
        "address": {
            type: Seq.STRING(255),
            field: "address"
        },
        "city": {
            type: Seq.STRING(255),
            field: "city"
        },
        "state": {
            type: Seq.STRING(255),
            field: "state"
        },
        "country": {
            type: Seq.STRING(255),
            field: "country"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.jobXLocation",
        schema: "public",
        table: "job_x_location",
        source: "generator",
        details: {
            as: "fkJobXLocation1s",
            foreignKey: "location_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.jobs",
        schema: "public",
        table: "jobs",
        source: "generator",
        details: {
            as: "fkJobXLocation1Jobs",
            foreignKey: "location_id",
            otherKey: "job_id",
            through: "job_x_location",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};