/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'companies.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'companies.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./companies.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkJobsXCompany1s").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.companies",
    options: {
        tableName: "companies",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "companies_pkey"
        },
        "shortName": {
            type: Seq.TEXT,
            field: "short_name"
        },
        "name": {
            type: Seq.TEXT,
            field: "name"
        },
        "createdAt": {
            type: Seq.DATE,
            field: "created_at",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updated_at",
            allowNull: false
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deleted_at"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.jobsXCompany",
        schema: "public",
        table: "jobs_x_company",
        source: "generator",
        details: {
            as: "fkJobsXCompany1s",
            foreignKey: "company_id",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.jobs",
        schema: "public",
        table: "jobs",
        source: "generator",
        details: {
            as: "fkJobsXCompany1Jobs",
            foreignKey: "company_id",
            otherKey: "job_id",
            through: "jobs_x_company",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }]
};