/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'job_x_location.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'job_x_location.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./job_x_location.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("job").onDelete = 'CASCADE'; 
util.getAttribute("jobId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.jobXLocation",
    options: {
        tableName: "job_x_location",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "jobId": {
            type: Seq.INTEGER,
            field: "job_id",
            primaryKey: true,
            allowNull: false,
            unique: "job_x_location_pkey",
            references: "public.jobs",
            referencesKey: "job_id"
        },
        "locationId": {
            type: Seq.INTEGER,
            field: "location_id",
            primaryKey: true,
            allowNull: false,
            unique: "job_x_location_pkey",
            references: "public.jobLocations",
            referencesKey: "location_id"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.jobs",
        schema: "public",
        table: "jobs",
        source: "generator",
        details: {
            as: "job",
            foreignKey: "job_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.jobLocations",
        schema: "public",
        table: "job_locations",
        source: "generator",
        details: {
            as: "location",
            foreignKey: "location_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};