/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'jobs.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'jobs.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./jobs.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkJobRefs").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.jobs",
    options: {
        tableName: "jobs",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "jobs_pkey"
        },
        "shortName": {
            type: Seq.TEXT,
            field: "short_name"
        },
        "content": {
            type: Seq.TEXT,
            field: "content"
        },
        "type": {
            type: Seq.TEXT,
            field: "type"
        },
        "modelType": {
            type: Seq.TEXT,
            field: "model_type"
        },
        "name": {
            type: Seq.TEXT,
            field: "name"
        },
        "publicationDate": {
            type: Seq.DATE,
            field: "publication_date",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "created_at",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updated_at",
            allowNull: false
        },
        "deletedAt": {
            type: Seq.DATE,
            field: "deleted_at"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.jobRefs",
        schema: "public",
        table: "job_refs",
        source: "generator",
        details: {
            as: "fkJobRefs",
            foreignKey: "job_id",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.jobsXCategory",
        schema: "public",
        table: "jobs_x_category",
        source: "generator",
        details: {
            as: "fkJobsXCategories",
            foreignKey: "job_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.jobsXCompany",
        schema: "public",
        table: "jobs_x_company",
        source: "generator",
        details: {
            as: "fkJobsXCompanies",
            foreignKey: "job_id",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.jobsXTag",
        schema: "public",
        table: "jobs_x_tag",
        source: "generator",
        details: {
            as: "fkJobsXTags",
            foreignKey: "job_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.jobXLocation",
        schema: "public",
        table: "job_x_location",
        source: "generator",
        details: {
            as: "fkJobXLocations",
            foreignKey: "job_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.jobCategories",
        schema: "public",
        table: "job_categories",
        source: "generator",
        details: {
            as: "fkJobsXCategoryCategories",
            foreignKey: "job_id",
            otherKey: "category_id",
            through: "jobs_x_category",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.companies",
        schema: "public",
        table: "companies",
        source: "generator",
        details: {
            as: "fkJobsXCompanyCompanies",
            foreignKey: "job_id",
            otherKey: "company_id",
            through: "jobs_x_company",
            onDelete: "CASCADE",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.jobTags",
        schema: "public",
        table: "job_tags",
        source: "generator",
        details: {
            as: "fkJobsXTagTags",
            foreignKey: "job_id",
            otherKey: "tag_id",
            through: "jobs_x_tag",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.jobLocations",
        schema: "public",
        table: "job_locations",
        source: "generator",
        details: {
            as: "fkJobXLocationLocations",
            foreignKey: "job_id",
            otherKey: "location_id",
            through: "job_x_location",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};