/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'job_tags.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'job_tags.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./job_tags.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("fkJobsXTag1s").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.jobTags",
    options: {
        tableName: "job_tags",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "job_tags_pkey"
        },
        "tag": {
            type: Seq.STRING(255),
            field: "tag"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.jobsXTag",
        schema: "public",
        table: "jobs_x_tag",
        source: "generator",
        details: {
            as: "fkJobsXTag1s",
            foreignKey: "tag_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.jobs",
        schema: "public",
        table: "jobs",
        source: "generator",
        details: {
            as: "fkJobsXTag1Jobs",
            foreignKey: "tag_id",
            otherKey: "job_id",
            through: "jobs_x_tag",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};